kind: Service
apiVersion: v1
metadata:
  name: sample-app
  namespace: sample-app
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: sample-app
